services:
  ptm_bmup_finance:
    container_name: ptm_bmup_finance
    build: .
    expose:
      - "3300"
    volumes:
      - ./src:/usr/src/app/src
      - ./storage:/usr/src/app/storage
    depends_on:
      - ptm_bmup_finance_db
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - PORT=${PORT}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
      - APM_SERVER_URL=${APM_SERVER_URL_DOCKER}
      - APM_API_KEY_FINANCE=${APM_API_KEY_FINANCE}
      - APP_APM_ACTIVE=${APP_APM_ACTIVE}
      - TZ=Asia/Jakarta
      - API_URL_CORE=${API_URL_CORE_DOCKER}
      - API_URL_SETTING=${API_URL_SETTING_DOCKER}
      - APP_FRONTEND_URL=${APP_FRONTEND_URL}
      - APP_URL=${APP_URL}
    networks:
      - ptm_bmup_finance_network
      - global_backend_network

  ptm_bmup_finance_db:
    image: postgres:17.2
    container_name: ptm_bmup_finance_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Jakarta
    volumes:
      - postgresptmbmupfinance:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - ptm_bmup_finance_network

  ptm_bmup_finance_nginx:
    image: nginx:1.27.3-alpine-slim
    container_name: ptm_bmup_finance_nginx
    ports:
      - "3300:80"  # Akses aplikasi di http://localhost:3300
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./storage:/var/www/storage:ro
    depends_on:
      - ptm_bmup_finance
    networks:
      - ptm_bmup_finance_network
      - global_backend_network

volumes:
  postgresptmbmupfinance: {}

networks:
  ptm_bmup_finance_network:
    driver: bridge
  global_backend_network:
    external: true

